### ISSUE TITLE
Change this 

### ISSUE THREAD

**Issue by Flattty** [Nightcore3996/purge#1]
So in the code theres a piece that has this `message.channel.fetchMessages` you should change that to `message.channel.messages.fetch` so it can work since Discord v12 doesn't support it or use it

**Comment by Shedhatch** [comment]
Hey there, 

To clarify, my whole code Is running under discord V11 and I'm having no plans on updating It. 
However, I've updated the Readme file to indicate that the current code version isn't up to date. 

Thanks ! 
Ps My apologies for the late response, I'm not using Github often.
